language: python
python:
  - "2.7"

before_install:
  - sudo apt-get build-dep python-numpy

install:
  - "dev/bootstrap.sh --venv $VIRTUAL_ENV"

script:
  - ./testall

notifications:
  email:
    - crosenth@uw.edu
